# 工作流名称
name: Docker Publish
concurrency:
  group: ${{ github.workflow }} # 使用工作流名称作为并发组的key
  cancel-in-progress: true # 取消任何正在进行的相同并发组的工作流

permissions:
  contents: write
  actions: write

# 触发工作流的事件
on:
  workflow_dispatch:
  push:
    branches:
      - main # 当 main 分支有 push 事件时触发

# 工作流运行的任务（jobs）
jobs:
  # 定义一个名为 'docker-release' 的任务
  docker-release:
    # 指定任务运行的虚拟环境
    runs-on: ubuntu-latest

    # 定义任务的步骤（steps）
    steps:
      # 步骤 1: 检出代码
      # 使用 actions/checkout@v4 拉取你的仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Checkout secret
        uses: actions/checkout@v4
        with:
          repository: ximplez/secret
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
          path: secret

      # 步骤 2: 设置 QEMU
      # 为了构建多平台镜像（可选，但推荐），需要设置 QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 步骤 3: 设置 Docker Buildx
      # Buildx 是一个 Docker CLI 插件，用于扩展构建功能，支持多平台构建等
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      # 里面会填充 env.REGISTRY
      - name: Log into registry
        if: github.event_name != 'pull_request'
        uses: ximplez/docker-login-action@master
        with:
          configPath: secret/common/docker_registry.json
          configKey: Ali-shenzhen

      # 步骤 5: 构建并推送 Docker 镜像
      # 使用 actions/build-push-action@v5 来执行构建和推送
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Dockerfile 的上下文路径（. 代表项目根目录）
          file: ./dockerfile # Dockerfile 的路径
          push: true # 设置为 true，构建后会推送到仓库
          tags: | # 为镜像设置多个标签
            ${{ env.REGISTRY }}/cf-ddns-node:latest
            ${{ env.REGISTRY }}/cf-ddns-node:sha-${{ github.sha }}

  deploy:
    needs: docker-release

    # 运行环境
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    # 运行步骤
    steps:
      - uses: actions/checkout@v4
      - name: Checkout secret
        uses: actions/checkout@v4
        with:
          repository: ximplez/secret
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
          path: secret
      - name: ready deploy
        run: |
          pwd
          mkdir deploy
          cp -r secret/cfCdn/deploy_config.json deploy/
          cp -r secret/common/* deploy/
          ls -l deploy
        # 部署到服务器
      - name: deploy
        uses: ximplez/ssh-deploy@main
        env:
          DEPLOY_CONFIG_PATH: deploy/deploy_config.json
          SSH_CMD_CONFIG_PATH: deploy/ssh_cmd.json

  delete_old_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 3
          keep_minimum_runs: 8
